### ISSUE TITLE
how many star printer does it support ? and which ones?

### ISSUE THREAD

**Issue by subhash08** [relishmedia/RMLStarReceiptPrinter#3]

**Comment by PawelDecowski** [comment]
Hi @subhash08 

We’ve only tested it on the SM-S220i but it should work with most Star printers that use the same paper width.

**Comment by subhash08** [comment]
@PawelDecowski 
thanks for your reply. 
what paper width does it supports ?

**Comment by subhash08** [comment]
hello @PawelDecowski
 does it support images?

**Comment by PawelDecowski** [comment]
No, text only at the moment.

Images are on the wishlist, but we won’t implement them until we need it for our own use, or there’s enough interest from other developers (there is none at the moment).
